### ISSUE TITLE
Package webextension for Safari?

### ISSUE THREAD

**Issue by ideabucket** [insin/control-panel-for-twitter#114]
Now that Apple's adopted the [WebExtension API][api], could the extension be made available for Safari? Or is Apple's implementation missing required functionality?

[api]: https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility

**Comment by insin** [comment]
It should work fine on Safari, (and in the iPhone version too, I think) but Apple doesn't support the same .zip file distribution that's used in all the other extension stores - you need a Mac to package it in XCode and a $100-a-year developer account.

If someone wants to donate about $3000 AUD to get those I'd happily build it 😸

**Comment by ideabucket** [comment]
It doesn't solve the developer account problem but I wonder if [Macstadium's free hosted Mac for open source software][1] would remove the need for you to own a Mac?

[1]: https://www.macstadium.com/opensource

**Comment by insin** [comment]
I'm trying to make the options page look more at home in Safari - how's this for the desktop version?

<img width="475" alt="Screenshot 2023-01-21 at 4 40 28 am" src="https://user-images.githubusercontent.com/226692/213843711-4ab0e68e-dd9b-4fe2-9577-3091cccbf0e5.png">
<img width="469" alt="Screenshot 2023-01-21 at 4 40 42 am" src="https://user-images.githubusercontent.com/226692/213843724-cf9ac559-87a2-47e2-bf64-31f4d419799b.png">
<img width="471" alt="Screenshot 2023-01-21 at 4 40 56 am" src="https://user-images.githubusercontent.com/226692/213843728-ea76b76b-0392-4b70-adc1-edab6b3d4b25.png">
<img width="466" alt="Screenshot 2023-01-21 at 4 41 11 am" src="https://user-images.githubusercontent.com/226692/213843733-ed205166-3f98-4c33-9897-a5e4e129454f.png">

**Comment by ideabucket** [comment]
I take it this is all one long scrolling panel? It's quite a lot to take in, but given Apple forces you into a popover I think it's as usable as it could be.

I don't know how much control you have over the styling of the options page, or whether the effort involved would be worth it, but a way to make it less visually overwhelming, if technically posisble, might be to use iOS-style drilldowns the way 1Blocker does:

<img width="354" alt="Screenshot 2023-01-21 at 16 12 38" src="https://user-images.githubusercontent.com/845818/213844849-1158a175-afaf-4dc7-9777-73fb2f6b329e.png">

**Comment by insin** [comment]
That would be a much larger effort, initially I'm just styling the same options page for all versions of the extension, but something to consider after the initial port.

In the middle of doing the iOS version, in which the dropdowns are particularly brutal compared to the native drilldowns 🙈 

![Screenshot 2023-01-21 at 6 48 11 am](https://user-images.githubusercontent.com/226692/213847695-d15b4c4a-14ce-4ebb-9a30-acd2729ee8fb.png)
