### ISSUE TITLE
Option to revert text size for tweets after Longer Tweets

### ISSUE THREAD

**Issue by mcpower** [insin/control-panel-for-twitter#236]
Twitter recently added Longer Tweets, which also changed the text size of tweets when focused:

![image](https://user-images.githubusercontent.com/6015058/218070665-113376e6-5733-4086-9174-af4ba871d847.png)

Some users might want to revert this change.

**Comment by insin** [comment]
He Who Shall Not Be Told Why His Numbers Are Tanking says it's getting fixed next week, they might do something about the new formatting applying to non-long tweets too:

https://twitter.com/elonmusk/status/1624009630778298370
