### ISSUE TITLE
Default to LATEST tweets and not TOP

### ISSUE THREAD

**Issue by JimDop** [insin/control-panel-for-twitter#237]
for some ridiculous reason twitter does not let you default to latest tweets on a search.   How about making that an option.

**Comment by insin** [comment]
Testing:

<details>
<summary>Mobile</summary>
<img src="https://user-images.githubusercontent.com/226692/218260304-d743ec9d-0145-4c7a-8fb9-206f96494502.gif">
</details>


<details>
<summary>Desktop</summary>
<img src="https://user-images.githubusercontent.com/226692/218260309-920af77f-9279-4940-9f61-39e23a00e908.gif">
</details>
