### ISSUE TITLE
"More Tweets" not being hidden again

### ISSUE THREAD

**Issue by ArthurusDent** [insin/control-panel-for-twitter#244]
This bug seems to be back: #97 

As explained here https://github.com/insin/control-panel-for-twitter/issues/97#issuecomment-1213512040 this only seems to happen when I'm not logged in and the URL contains tracking information. 

#### Settings:
![addon-settings-Screenshot 2023-03-02 105331](https://user-images.githubusercontent.com/6848629/222395952-41e9abcc-710a-456c-ab50-f8c9b5206c5d.png)

#### Screenshot:
![Screenshot 2023-03-02 at 11-00-25 Jessica Pin auf Twitter](https://user-images.githubusercontent.com/6848629/222395961-8fc06f17-754b-4906-8f02-e6bd39a18b10.png)

System: Windows 10
Browser: Firefox 110.0

**Comment by insin** [comment]
This has been replaced with "Discover more", which we're currently able to hide and will keep fixing as Twitter changes break it
