### ISSUE TITLE
Legacy Verified being removed april 1st

### ISSUE THREAD

**Issue by TylerGlaiel** [insin/control-panel-for-twitter#253]
https://twitter.com/verified/status/1639029459557679104

Expecting this to happen suddenly I have previously scraped a list of all legacy verified account ids (its every account @verified follows on twitter). Could be useful for continuing to distinguish paid verified accounts from legacy accounts once its deprecated. You may wish to scrape it yourself if you don't trust the file I've uploaded, it may not be the same if accounts have been deactivated or changed their name since I last scraped it.

https://github.com/TylerGlaiel/TwitterLegacyVerifiedData

**Comment by sawayoshisy** [comment]
Looks like current implementation makes it impossible to discern whether an account is a legacy verified or blue verified account; the two checks have been consolidated into one that says "subscribed to Twitter Blue or... legacy verified account". The scraped list might be helpful for any implementation of a legacy list, though it also seems like quite a bit of an undertaking to add...?
