### ISSUE TITLE
app store compatibility?

### ISSUE THREAD

**Issue by lazydaizy** [insin/control-panel-for-twitter#256]
CPFT is only the second safari extension i've bought, as i use firefox primarily on desktop, so my experience with their cross device usage is very limited and i may have missed something; however, the previous extension [dark reader] i bought was 1 payment and it was functional on macos, ipados, and ios. i assumed this was going to be the case with CPFT too, and the layout of the app store listing strongly corroborated that. however, after buying the extension on my mac (i was bein lazy cos its the only device i have with a finger print sensor lmao) i found that i was unable to access the extension on ipad or iphone at all, and it is only after buying that i found anywhere that showed it was apparently a mac-only extension if bought here. my only option is to purchase it again, which i am gonna hold off on until the refund is hopefully allowed. 

is the purchase even functioning as intended, because literally nothing on the app store page that i could find suggests that it is 2+ separate device dependant extensions - the listing literally shows all of them in the compatibilities! - , and tbh it left me feelin a bit stupid and i would just like some clarity pls :') 

thank u for the baller extension she's been keepin me sane for years, pls let me know if this is an issue i need to mention to apple instead or smth i guess

**Comment by insin** [comment]
It should work as you've said, buying the app gets you all versions for all platforms.

I'd definitely ask Apple support why it's not working for you - their term for how it's sold for multiple platforms is "[Universal Purchase](https://developer.apple.com/support/universal-purchase/)"

**Comment by lazydaizy** [comment]
oh i'm glad to know, thank u!!
