### ISSUE TITLE
Retweets appearing in timeline even when turned off.

### ISSUE THREAD

**Issue by StudioSyndiCatCaius** [insin/control-panel-for-twitter#258]
As the title says. I have retweets set to "Hide" or "Show in Separate Tab". They also show up as normal tweets, not showing who even retweeted them.

**Comment by KlooKloo** [comment]
Looks like Elon removed the "Retweeted by XXXX" label on the TL.

**Comment by insin** [comment]
This appears to have been a brief Twitter blip a few weeks ago
