### ISSUE TITLE
Seeing user likes on " Following " tab

### ISSUE THREAD

**Issue by quizotix** [insin/control-panel-for-twitter#259]
On my " Following " tab, I see liked tweets now from what I'm presuming are people I follow instead of just their Twitter posts. Is there anyway to add a third tab maybe called " liked tweets "  to separate them from the " Following tab? "

Currently the tabs I have enabled on my UI are " Following " (theoretically only for tweets from people I follow) and " Retweets "(retweets from people I follow).  

Edit: Turns out, these may also be Retweets from people I follow which makes sense since my retweet tab is currently broken and does not show anything. Any fixes?

**Comment by h3ll0-w00rld** [comment]
Twitter updated something, which completely broke the Control Panel, give the devs few days or weeks to fix it. Since funny backend moment.

**Comment by insin** [comment]
This appears to have been a brief Twitter blip a few weeks ago
