### ISSUE TITLE
Feature request: Replace share links with links to fxtwitter

### ISSUE THREAD

**Issue by SDCore** [insin/control-panel-for-twitter#262]
For Discord users, fxtwitter is a replacement for regular twitter link embeds. You can actually [see the feature in action here.](https://github.com/FixTweet/FixTweet). It shows more info, allows for more pics to be embedded, and allows for videos to be embedded as well. Having a toggle to replace twitter.com links with fxtwitter.com using the share > "copy link to tweet" function would be an amazing addition.

**Comment by insin** [comment]
Sorry, too niche for this extension, this would be better implemented in a dedicated extension
