### ISSUE TITLE
Feature Request: Set Twitter logo

### ISSUE THREAD

**Issue by frameset** [insin/control-panel-for-twitter#264]
Following Musk changing the logo to a dog for what was clearly supposed to be an April Fool's joke that his skeleton crew of workers couldn't get done in time, it would be nice to be able to set the logo ourselves via the extension.

**Comment by marypcbuk** [comment]
pretty please with dogs on, let me change this excrescence to something else!

**Comment by coolandsmartrr** [comment]
Looks like it's addressed with this commit:
https://github.com/insin/control-panel-for-twitter/issues/260

**Comment by tsunaobou** [comment]
@marypcbuk It says that the logo has been fixed in [v3.3.3](https://github.com/insin/control-panel-for-twitter/releases/tag/v3.3.3). 
But even though it is v3.3.3 in the Chrome extensions store, I don't see an option to change the logo. 
Is there such an option in the Eng version?
