### ISSUE TITLE
"Manifest file has corrupted" when I tried to install from edge / chrome store

### ISSUE THREAD

**Issue by yeonggille** [insin/control-panel-for-twitter#267]
Hello, I hope you doing well.
When I tried to install this wonderful plugin from the edge / chrome addon store on edge latest version, it keep says
"Manifest file from this addon has corrupted and can't be installed in this browser"
How could I solve this problem? Thank you, have a good day

**Comment by insin** [comment]
I'm unable to replicate this (tried installing in Edge from Chrome Web Store and Edge Add-ons on both Mac and Windows) and I can't find any reference to the error message anywhere else, so I'm afraid there's not much I can do.

**Comment by yeonggille** [comment]
I was used Ramdisk with Browser temp, and it was the problem.
Ramdisk program had some kind of overflow today and ouccured the glitches. 
the problem is now solved, and thanks for the reply. have a nice day
