### ISSUE TITLE
Volume Slider not appearing on Desktop.

### ISSUE THREAD

**Issue by Zachruff** [insin/control-panel-for-twitter#272]
For some reason when using twitter on firefox, a few days ago on my windows 10 desktop the volume slider just wouldnt appear anymore when I hover my mouse over the volume button. It will only let me click it so I can only mute/unmute videos but not actually control the volume. Oddly it was still like this even when disabling adblock/control panel. It also does NOT happen on my Windows 10 Laptop with firefox which is even stranger, so on the laptop im still able to adjust the volume like normal.

**Comment by insin** [comment]
> Oddly it was still like this even when disabling adblock/control panel

I don't think this is related to this extension
