### ISSUE TITLE
Accounts with tweet notifications dont notify anymore.

### ISSUE THREAD

**Issue by Zachruff** [insin/control-panel-for-twitter#274]
I followed my alt account from my main and turned on notifications for its tweets. I then tweeted on my alt. On my main I got a notification icon on the bell but when clicking on the notifications tab there was nothing new there.

**Comment by insin** [comment]
Notifications on Twitter have been broken like this for months now - the Notifications page lags behind the notification icon count and usually takes a refresh to load brand new notifications
