### ISSUE TITLE
Ability to hide things a user retweeted

### ISSUE THREAD

**Issue by Matt-Sredojevic** [insin/control-panel-for-twitter#276]
Currently while allowing retweets to be seen in the regular timeline, i can see posts dupilicated when i retweet them
![image](https://user-images.githubusercontent.com/14945398/233448369-f3d44a56-76c8-404f-aff7-0964c3269e31.png)
the ability to hide the retweet that is from the user could be nice

**Comment by insin** [comment]
This is too specific a feature to add when we already offer the ability to hide or move retweets to a different timeline

We also recommend using the green herb and health spray at the same time, here's an IRL example: https://youtu.be/pDTpRXJy6C4?t=1276
