### ISSUE TITLE
Request: Bring back twitter video trimmer

### ISSUE THREAD

**Issue by dnestico** [insin/control-panel-for-twitter#286]
Couldn't find a better screenshot on Google but twitter used to have a helpful video trimmer which was removed in the new UI.

Would be cool to get it back.

![tweet-a-video-1-2](https://user-images.githubusercontent.com/3034555/233748965-f1ac4012-402d-4677-ac7d-8592522cf673.jpg)

**Comment by insin** [comment]
Sorry, we can't restore old functionality which has been removed from Twitter itself
