### ISSUE TITLE
Request: Option to show legacy verified users

### ISSUE THREAD

**Issue by derLesh** [insin/control-panel-for-twitter#289]
Since the old legacy blue checkmarks are gone, it would be great to have an option to restore those via a list.
The csv file might be too large to include directly in the extension, but allowing the user to add the file manually might be a workaround.

Example list:
https://gist.github.com/travisbrown/b50d6745298cccd6b1f4697e4ec22103

**Comment by insin** [comment]
Someone's already made another extension for this:

https://github.com/luiserdef/twitter-real-verified
