### ISSUE TITLE
Bug: Loaded tweets from infinite scroll in a thread have regular checkmark

### ISSUE THREAD

**Issue by dev0T** [insin/control-panel-for-twitter#292]
How to reproduce: Go to a thread with many twitter blue subscribers and start blocking them. After a few the icon will be the regular checkmark icon.

Edit: Okay, I tried reproducing it and it appears to be linked to the infinite scroll when it loads new thread replies. The old replies that were loaded still had the changed icon but the new loaded tweets had the usual check mark.

**Comment by insin** [comment]
When I was testing hiding blue replies in threads (still in development), I discovered Twitter was sometimes inserting completely empty elements into the thread timeline, which I haven't seen before in the main timeline.

This was causing an error which would prevent new tweets from being processed, which is probably the cause of this.
