### ISSUE TITLE
Feature: Revert comment order algorithm

### ISSUE THREAD

**Issue by Zachruff** [insin/control-panel-for-twitter#293]
Recently, the algorithm that chooses which comments on a post to display first has changed and now you will almost always see every reply from a twitter blue user before seeing replies from anyone else. If not possible to revert this change, a feature to hide any replies from twitter blue users would be nice as well.

**Comment by insin** [comment]
Can't do anything about the order, but working on hiding the replies

**Comment by Zachruff** [comment]
> @insin It'd be great if those replies could be hidden if-and-only-if one does not follow the replying account. The top replies are usually mostly engagement/crypto spam, but some accounts might be legitimate.

agreed, or even just have a setting to choose if you want to hide all blue accounts or only non-followed blue accounts

**Comment by mariomadproductions** [comment]
> Can't do anything about the order, but working on hiding the replies

Could the order be fixed if the extension retrieved all the comments (e.g. by doing the scrolling down/"show more" processs), then reordering and displaying them?

**Comment by insin** [comment]
Blue replies can now be hidden as of v3.8.1
