### ISSUE TITLE
Bug: Hide Views setting breaks the spacing between username and post time on QRTs

### ISSUE THREAD

**Issue by morellam-dev** [insin/control-panel-for-twitter#296]
Ordinarily, Twitter adds an element containing just the string ` · ` between the username and date of a quoted tweet. However, if hideViews is enabled, that element is hidden, resulting in no space:

![image](https://user-images.githubusercontent.com/4561733/234686082-bc5d73a4-9016-4dcf-9e46-87d51b2f5e6c.png)
On my browser, that element is hidden by the selector `[data-testid="tweet"][tabindex="-1"] div[aria-hidden="true"]:nth-child(2):nth-last-child(2)` defined here. I suspect it needs to be specified further. https://github.com/insin/control-panel-for-twitter/blob/ea29f0d29dcd03cc01034dee08bd198d97194b4b/script.js#L1918-L1924

![image](https://user-images.githubusercontent.com/4561733/234687853-0c653207-a7a1-40a4-9d8c-d47a32c3e79f.png)

**Comment by insin** [comment]
The joys of modifying a React Native for Web app without touching the DOM.
