### ISSUE TITLE
Request: Hide "This tweet is from an account you blocked - View tweet" labels

### ISSUE THREAD

**Issue by onthegoldenpath** [insin/control-panel-for-twitter#301]
These ought to be hidden by default if possible, as it defeats the purpose of blocking the blue checks if they still appear on top
![image](https://user-images.githubusercontent.com/14057810/236323396-1906c370-4328-4e48-8cd1-9ccd008be0bf.png)

**Comment by dt10111** [comment]
seconded

**Comment by magnushammar** [comment]
and muted words and accounts. I have muted threadreaderapp-spam as good as I can, but now Twitter gives me pages of  feedback telling me that I have hid what I wanted to hide. :rofl:

**Comment by Cimiteriophiliac** [comment]
+1. Hard to believe twitter is making such idiotic interface decisions, would love to see this fixed.
