### ISSUE TITLE
Feature: Show full tweets in timeline without having to click "show more"

### ISSUE THREAD

**Issue by Cimiteriophiliac** [insin/control-panel-for-twitter#303]
Longer tweets get cut off and I have to click on them to read them in full, which is very annoying.

![Capture](https://user-images.githubusercontent.com/57408125/236790200-56a55bd0-9411-48e7-a30f-d8cd1fe905c5.PNG)

**Comment by Cimiteriophiliac** [comment]
@jdschuitemaker Yeah, maybe. I'd imagine it should still be possible if the plugin can somehow open the links in the background, but on the other hand I don't know what I'm talking about 😅

**Comment by insin** [comment]
Sorry, we can't implement this as Twitter doesn't have a convenient way to get the rendered version of the expanded tweet
