### ISSUE TITLE
Request: Hide Retweets in pinned lists

### ISSUE THREAD

**Issue by Rukomura** [insin/control-panel-for-twitter#307]
Hello there,
I don't know if there's already an option for this that I overlooked, but I noticed when I click on pinned lists in my timeline, I see retweets even when I've disabled them with the "Hide Retweets" option from the "Lists" tab. 
It would be nice if this option worked on pinned lists too without hiding retweets as a whole.

**Comment by insin** [comment]
We should probably expose the `listRetweets` setting in the settings UI - currently you can only change it in this custom item we add to the menu when viewing a list - it could then apply to pinned lists without it being confusing why they're being hidden, as it;ll be visible in settings. Not sure why I did it this way 😸 

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/ce7254bd-58ef-4535-ac67-4cd6dbf2d215)
