### ISSUE TITLE
Feature request: removal of the "open in App" banner (iOS)

### ISSUE THREAD

**Issue by pluslatte** [insin/control-panel-for-twitter#311]
There is an annoying banner on top of the page in Safari-version Twitter web page.
![image](https://github.com/insin/control-panel-for-twitter/assets/103520205/2d8197a5-eda2-440e-85fa-7593e79b99b2)

This thing disappears when you are using the PWA, but currently it seems like no Safari add-on works in the PWA.

I would appreciate it if you could add this feature.

**Comment by insin** [comment]
I can't get this to appear so I can block it - is this just always there for you?

I've tried logging out and in as that usually prompts Twitter to annoy you with things like this, but it didn't work for me.

**Comment by pluslatte** [comment]
Yes, this banner is always there. It doesn't stick with scrolling. It stays on the top of the page.

**Comment by b-wind** [comment]
I think it is probably called a Smart App Banner.

https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners

**Comment by insin** [comment]
If that's the solution, closing this for now - we can put this in as a FAQ somewhere
