### ISSUE TITLE
Option to hide Tweets from "Twitter Blue" accounts

### ISSUE THREAD

**Issue by benui-dev** [insin/control-panel-for-twitter#312]
Kind of self-explanatory, it would be great to hide any Tweets from people subscribed to Twitter Blue.

**Comment by Cimiteriophiliac** [comment]
+1, most of these comments don't deserve being at the top of the list.

**Comment by insin** [comment]
> Just a white list for those who you're following, any other Blue account should be hidden.

This is the problem - the interface doesn't expose any information on which accounts you're following, and you don't really want an extension doing something like opening the context menu on every tweet in a thread every time it changes to check if you're following them.

**Comment by insin** [comment]
An initial version of this has been done in eb378c9a1d8bd4a78df031006647b555c75b3c73 - when you're viewing an individual tweet's thread it currently just hides direct replies from Twitter Blue users (unless it's the author of the focused tweet replying to themselves)

**Comment by insin** [comment]
- [ ] Don't hide any tweets above the focused tweet (if the focused tweet is a reply there can be a thread of tweets above it) - focusing on a reply to a Twitter Blue tweet currently results in the focused tweet and everything above it being hidden (unless the focused tweet is a Twitter Blue user replying to themselves - fun!)
