### ISSUE TITLE
Hide the "Get Verified" window on the top right side

### ISSUE THREAD

**Issue by MetroidCatcher** [insin/control-panel-for-twitter#319]
Seems to be only in Home timeline so far.
![waterfox_2023-06-08_21-23-39](https://github.com/insin/control-panel-for-twitter/assets/16920375/fa7d2904-925d-42d5-a3b7-7ec333c5eb4a)

**Comment by aubymori** [comment]
I second this. I can't seem to hide this with only CSS without interfering with other parts of the site.

**Comment by insin** [comment]
It's already being hidden if you use this setting (the "etc." is doing a lot of work)

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/a5223178-51cf-41c0-a7bf-0d888e2b73a0)

**Comment by aubymori** [comment]
> It's already being hidden if you use this setting (the "etc." is doing a lot of work)
> 
> ![image](https://user-images.githubusercontent.com/226692/244524286-a5223178-51cf-41c0-a7bf-0d888e2b73a0.png)

i don't want to hide those, only the verified thing

**Comment by Rocket3192** [comment]
> 

Yes but it also hides the top tweets and we want to keep those
