### ISSUE TITLE
Separate verified accounts with 1 Million followers/Affiliates from Twitter Blue Subscribers

### ISSUE THREAD

**Issue by DeathRabbit-X** [insin/control-panel-for-twitter#320]
Hi! Wanted to make a post on here because I absolutely LOVE and appreciate what you've been doing to modern day Twitter with the Control Panel. I have no clue how to do any of this stuff that goes to making it all work so well so I wanted to make a suggestion. 
As far as I know, all accounts that get 1 million followers get Twitter Blue for free and accounts that are affiliated also have a Twitter Blue logo sometimes. If there is a way to let those accounts keep the old checkmark and have people that actually pay for Blue to have the logo, that'd be awesome. Regardless, love everything you've been doing with the Control Panel, keep it up!

**Comment by insin** [comment]
Not planning to add this as it'd require doing a lot more work everywhere a check mark can appear to check the details of the account, however in the next release users with more than 1 million followers won't be hidden by default using the new "Hide Twitter Blue replies" feature #312
