### ISSUE TITLE
Revanced Patch?

### ISSUE THREAD

**Issue by dnestico** [insin/control-panel-for-twitter#322]
Hi, really love your extension and would love to have its features on the twitter app since as of yesterday even my own API key I was using on a 3rd party app finally died. Not sure if you are aware of what Revanced is but if you are I would love for this extension to be also created as Revanced Patch pls, since there aren't many patches available atm for twitter. Thanks.

Links:

https://revanced.app/patches/com.twitter.android
https://revanced.app/docs

**Comment by insin** [comment]
> https://revanced.app/patches/com.twitter.android

"This page received a cease and desist letter from a multi-billion dollar tech company"

Count me out of that :)

**Comment by dnestico** [comment]
Well that was not the case last night LOL, still using Twitter Revanced and also YouTube Revanced as we speak...
