### ISSUE TITLE
Retweet will be displayed

### ISSUE THREAD

**Issue by pikesaury** [insin/control-panel-for-twitter#328]
Retweet no longer appear in a separate tab as of today.
Could you please check?
![タイトルなし](https://github.com/insin/control-panel-for-twitter/assets/37852075/41914d41-53de-48a4-b2d9-3140c678febb)

**Comment by Yoksven** [comment]
Can confirm. Retweets are showing up in the "following" tab.

**Comment by insin** [comment]
Twitter deployed a change which broke all timeline functionality, which is being tracked in this issue: 327
