### ISSUE TITLE
Promoted tweets reappearing on mobile site

### ISSUE THREAD

**Issue by ghost573** [insin/control-panel-for-twitter#329]
Promoted tweets seem to have reappeared on mobile.
This behavior was seen on the latest userscript so it should be 3.8.0

![Screenshot_20230620-094141_Bromite_1](https://github.com/insin/control-panel-for-twitter/assets/108908286/0b86e2aa-511c-427e-b1a8-ba0d640055ee)

**Comment by insin** [comment]
Twitter deployed a change which broke all timeline functionality, which is being tracked in this issue: #327
