### ISSUE TITLE
twitter blue support

### ISSUE THREAD

**Issue by pikesaury** [insin/control-panel-for-twitter#342]
When I register for Twitter Blue, the number of items in the red frame increases.
So, is it possible to narrow the spacing between vertical items?
I cannot see the tweet button and feel inconvenienced.
Thank you for all your help.
![タイトルなし](https://github.com/insin/control-panel-for-twitter/assets/37852075/9f58869b-e271-459b-8f82-a0909da2f5e2)

**Comment by insin** [comment]
The next version will have a new "Navigation density" option which lets you change the amount of spacing

<img width="435" alt="Screen Shot 2023-07-09 at 3 53 25 pm" src="https://github.com/insin/control-panel-for-twitter/assets/226692/b382cedc-53e5-4938-9366-244b9ec681a8">


| Default | Comfortable | Compact |
| - | - | - |
| <img width="77" alt="Screen Shot 2023-07-09 at 3 54 27 pm" src="https://github.com/insin/control-panel-for-twitter/assets/226692/b8ce6f43-6c84-4f36-a5ff-bc76350d9273">  | <img width="77" alt="Screen Shot 2023-07-09 at 3 55 14 pm" src="https://github.com/insin/control-panel-for-twitter/assets/226692/eed6d97e-2c04-4d6c-963e-b0b6d90bade7"> | <img width="77" alt="Screen Shot 2023-07-09 at 3 55 20 pm" src="https://github.com/insin/control-panel-for-twitter/assets/226692/3e46e357-af69-4e0d-a55d-17c7dd7071c8">  |

**Comment by pikesaury** [comment]
Thank you very much!
