### ISSUE TITLE
x.com nonsense

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#356]
Started adding some guesses to changes which will be needed in this branch:

https://github.com/insin/control-panel-for-twitter/compare/master...x

**Comment by pixiekat** [comment]
petition to have the addon use the old logo and replace all instances of the garbage new name with Twitter 😀

**Comment by marypcbuk** [comment]
is 3.12.0 waiting for Microsoft Store approval? I know it's stupid and petty but that damn logo is annoying me SOOOO much and I knew you'd be on top of this!

**Comment by insin** [comment]
@marypcbuk Yes, but you should install the Chrome Web Store version in Edge if you want the latest any time soon. It's the exact same extension in both and Edge Add-ons usually takes days to approve new versions.

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/395326a5-bcce-4fd2-9cee-e61dd64c4663)

**Comment by marypcbuk** [comment]
> @marypcbuk Yes, but you should install the Chrome Web Store version in Edge if you want the latest any time soon. It's the exact same extension in both stores and Edge Add-ons usually takes days to approve new versions.
thanks! for security reasons I prefer not to enable alternate extension stores (because you can't tell Edge 'just the Google store' so enabling it means you could maybe be tricked into taking a malicious extension from a rando third party store - so I've used dev tools to entirely block the logo until the new release comes through

**Comment by Allanbuzzy** [comment]
Favicon has changed. Any chance of a "Replace X favicon with Twitter bird" option?

**Comment by scatterkeir** [comment]
The X favicon has just returned.

**Comment by HunterAhlquist** [comment]
The X logo in the favicon appears to be replaced, but the logo on the top of the menu remains.

**Comment by insin** [comment]
Twitter changed it again, fixed in v3.13.0

**Comment by insin** [comment]
Looks like we can - we're removing the styles we use to replace the loading indicator too early, which is causing these flashes; we can also make it use the last theme colour you used in the loading indicator

These are hard refreshes:

![firefox_MoNWaSD6Va](https://github.com/insin/control-panel-for-twitter/assets/226692/088f4718-d2a6-4837-b6ec-fe726f75ac27)

**Comment by nagato7** [comment]
![image](https://github.com/insin/control-panel-for-twitter/assets/12077847/620f0fa8-07c9-4101-850e-07baff25a9ac)
Don't know it can be changed with extension but It seems X changed site title to "X".

**Comment by Allanbuzzy** [comment]
They've also replaced "Tweet" with "Post", maybe another switch to add?

**Comment by insin** [comment]
Creating separate issues for these as the changes trickle out instead of adding to one undying mega-issue. "Posts" is being handled in #368
