### ISSUE TITLE
Replace X logo option not working. (Firefox)

### ISSUE THREAD

**Issue by MithelCelestia** [insin/control-panel-for-twitter#360]
I'm not sure what's supposed to happen with this option. I expected the X logo on the upper left corner to return back to the old Twitter Bird but there doesn't seem to be any change. I tried toggling it on and off while looking at the website to see if there's any effect but I don't see any change at all.
![Screenshot (59)](https://github.com/insin/control-panel-for-twitter/assets/42472766/9f65e35c-eb7e-434c-ae49-e91bd5ca26e5)

**Comment by insin** [comment]
Firefox Add-ons hasn't reviewed and published the new latest yet

https://twitter.com/ControlPanelFT/status/1684416287248904192
