### ISSUE TITLE
[Feature Suggestion]: Restore reason a Tweet shows up on the "For You" page

### ISSUE THREAD

**Issue by just-ero** [insin/control-panel-for-twitter#363]
## Description
At one point, Twitter (knowingly or unknowingly) removed the reason why a Tweet would show up on the user's "For You" page when it is not from an account they follow, or a retweet. Such Tweets are recommended to the user when:
- someone they follow liked another Tweet
- someone they follow follows an algorithmically similar account themselves

Below are some screenshots comparing how such Tweets show up on the timeline versus how they show up once such a Tweet is clicked.

![image](https://github.com/insin/control-panel-for-twitter/assets/56401411/0403ed44-2de6-40d3-bcb0-c055313c1c29)
![image](https://github.com/insin/control-panel-for-twitter/assets/56401411/4ee8c709-31fe-4112-aae8-cca010b22226)

---

It would be great if this reason could also be restored to the actual timeline.

**Comment by insin** [comment]
We can't restore this as the information needed is hidden away in a menu now
