### ISSUE TITLE
[Bug]: Hiding Retweets, Quote Tweets, Likes, and Following / followers metrics does not work correctly

### ISSUE THREAD

**Issue by just-ero** [insin/control-panel-for-twitter#365]
## Description

When opening a Tweet on its own page, hiding `Retweets`, `Quote tweets`, and `Likes` does not hide the word associated with the numbers (see screenshot below). This *does* work with `Bookmarks`.

![image](https://github.com/insin/control-panel-for-twitter/assets/56401411/d7eb68e5-438c-4e73-ae94-35f70e0876bd)

The same goes for `Following / followers` on profile pages.

![image](https://github.com/insin/control-panel-for-twitter/assets/56401411/a77351b1-a9e9-466a-8802-4756c740da3d)

## Additional Information

I also want to point out that these options below should perhaps be reordered into the same order as they are shown in the actual UI: `Retweets`, `Quote Tweets`, `Likes`.

![image](https://github.com/insin/control-panel-for-twitter/assets/56401411/bd8636aa-df74-4a7d-83e7-2489d2395df8)

**Comment by insin** [comment]
We only hide the numbers so we're not removing access to being able to view the things (which doesn't show you the numbers)

Half of these have now been moved to the new "Post engagements" screen by Twitter
