### ISSUE TITLE
Request: customize Twitter UI - reorder buttons etc, see links & pic in post

### ISSUE THREAD

**Issue by GreenDotBlue99** [insin/control-panel-for-twitter#372]
Neat extension called Twitter UI Customizer has some neat button reorder functionality. Similar would be great in CPFT - that other extension clashes with Control Panel for Twitter, compatibility issues.

![284699](https://github.com/insin/control-panel-for-twitter/assets/82726385/f00c3b46-5c27-45c0-b1f1-d5adfbcf21e4)

https://github.com/kaonasi-biwa/Twitter-UI-Customizer

https://chrome.google.com/webstore/detail/twitter-ui-customizer/hpmhdmlhnppmmipefebkhkbpdcjiidmh?hl=ja

**Comment by insin** [comment]
Doing this ourselves would create even more conflicts with other extensions which add new buttons to the UI (like #209 and #346)
