### ISSUE TITLE
Request: Replacing all mentions of "Post" in the site's UI with "Tweet"

### ISSUE THREAD

**Issue by christine6290** [insin/control-panel-for-twitter#376]
Twitter recently renamed the tweet button to say "Post" instead and "Post your reply" is now said instead of "Tweet your reply" and it seems that they'll rename both retweet to "repost" and quote tweet to "quote post" so is it possible to revert these changes back?

**Comment by insin** [comment]
This is being done in #368 - we'll create separate issues for the rest when they happen
