### ISSUE TITLE
[suggestion] Restore "actually verified" icon

### ISSUE THREAD

**Issue by TylerGlaiel** [insin/control-panel-for-twitter#377]
Twitter currently shows a "Verified since <date>" on twitter blue subs when you click the check. For accounts that were previously legacy verified, this date includes when they were originally verified. You can detect if an account is a blue-verified or legacy-verified account by checking if the date they were verified since was before november 2022

**Comment by insin** [comment]
There are other extensions which do this based on previously-scraped lists of verified users, this extension accepts that proper verification is dead
