### ISSUE TITLE
Option to hide or censor the "Review your phone" pop up

### ISSUE THREAD

**Issue by Pabszito** [insin/control-panel-for-twitter#384]
I originally thought of hiding the entire pop up, but there's also the option of rewriting the text shown on it to:

a) show only the two last digits of your phone number like most platforms do
b) completely hide the phone number

Original tweet that gave me the idea is https://twitter.com/zombie_girlietv/status/1688406520084459520 - it's not the first time I see something like this.

In case the Tweet gets deleted, this is its content:

> WARNING STREAMER FRIENDS, DO NOT BROWSE TWITTER WHILE YOU'RE LIVE!!
> 
> I just had this pop up without warning and it showed my whole god damn phone number without blanking anything out! Do not accidentally dox yourself!

![image](https://github.com/insin/control-panel-for-twitter/assets/37744843/2c69a0df-e638-41ba-843f-45f16efdf0db)

**Comment by insin** [comment]
I just got this, looks like they already fixed it.

![firefox_AF6FxGWkhF](https://github.com/insin/control-panel-for-twitter/assets/226692/9e4f24ea-74e3-4310-b270-490e9fffc99c)
