### ISSUE TITLE
More Tweet -> Post changes have landed in web

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#385]
![firefox_pSV4Nt3wEU](https://github.com/insin/control-panel-for-twitter/assets/226692/f2b2250d-6b43-4578-90e2-6c1beda74710)

![firefox_RifypttXCk](https://github.com/insin/control-panel-for-twitter/assets/226692/ca7cc9d1-231e-4660-abe8-71d3ae8e2be1)

![firefox_ig9QnpS5A1](https://github.com/insin/control-panel-for-twitter/assets/226692/f417d77b-60af-4014-ae49-d0e6b9f1b4fc)

**Comment by s-e-e-n** [comment]
<img width="154" alt="スクリーンショット 2023-08-14 18 57 29" src="https://github.com/insin/control-panel-for-twitter/assets/142062744/443a9770-7698-4195-ace9-b7f2fa28114a">
