### ISSUE TITLE
Possible bug: Quote Tweets no longer hidden on home timeline

### ISSUE THREAD

**Issue by centraletude** [insin/control-panel-for-twitter#393]
Despite having Quote Tweets disabled on my desktop timeline, I am able to view Quote Tweets on my timeline even after clicking on them—prior to this, even if one did show up on my timeline (which was rare and usually immediately upon loading the page), it would disappear after being clicked on. I tried disabling all my other extensions, triple-checked that I had Quote Tweets set to hide, and I checked the debug logs as well. Didn't see mention of them not working here or on Twitter itself so I thought I should make sure the issue was known.

Screenshot of my extension:
![image](https://github.com/insin/control-panel-for-twitter/assets/142633272/7a386963-e955-470f-86c0-02ce2eb1b24d)
Debug log:
[control-panel-for-twitter-v3.15.0.config.txt](https://github.com/insin/control-panel-for-twitter/files/12384332/control-panel-for-twitter-v3.15.0.config.txt)

Thank you so much for all your hard work, and I'm so sorry to be a bother.

**Comment by insin** [comment]
This will be fixed in the next verison
