### ISSUE TITLE
Explore tab reappears when in the Messages tab

### ISSUE THREAD

**Issue by dukeajc** [insin/control-panel-for-twitter#397]
Normally I have the Explore tab hidden, but while in my DM's it reappears. Interacting with it takes me to the blank search field.

**Comment by insin** [comment]
This is a setting so you always have access to search (when using "Hide Explore page contents and use it only for searching) when the sidebar isn't there, e.g. when using the full-width timeline option or on resolutions where there will never be a sidebar

If you want it to always be hidden, untick "Show when sidebar is hidden"

<img width="399" alt="Screen Shot 2023-08-23 at 5 21 35 pm" src="https://github.com/insin/control-panel-for-twitter/assets/226692/38f80455-5d6d-4364-9653-5c1c7fd446e2">
