### ISSUE TITLE
Regression: "Verified Orgs" appears in sidebar

### ISSUE THREAD

**Issue by justin** [insin/control-panel-for-twitter#401]
Hiding this looks like it was integrated in d48e7a68750381404561505ada1e277bd3d22d12, but as of recently it seems to appear at all times on the web.

**Environment**

- Control Panel for Twitter 3.15.3 (Mac App Store)
- Safari Version 17.0 (18616.1.27.101.1, 18616)
- macOS 13.5 (22G74)

**Steps to Reproduce**

1. Enable the Control Panel extension in Safari
2. Load twitter.com in a Safari window.
3. Notice that "Verified Orgs" shows up in the sidebar. 

![CleanShot 2023-08-23 at 11 14 14@2x](https://github.com/insin/control-panel-for-twitter/assets/1384/a63f1312-85f1-4571-bd14-300575421288)

**Additional Info**

I tried going through all the different options in the extension to see if I could trigger it hiding, but there doesn't seem to be a way presently.

**Comment by insin** [comment]
Can you confirm if the link is still `/i/verified-orgs-signup`?

They keep rotating this between Verified/Premium/Verified Orgs, so I'm just adding them to a list now instead of removing them when they make menu changes.

**Comment by justin** [comment]
Yeah. It links to `https://twitter.com/i/verified-orgs-signup` presently.
