### ISSUE TITLE
Promoted posts re-appearing?

### ISSUE THREAD

**Issue by ryandtw** [insin/control-panel-for-twitter#405]
Just had this on my iPhone. Promoted (ad) posts reappearing when I was searching on Twitter, even with use of Control Panel (this app) and Mullvad VPN's ad blocker.

Can anyone replicate this? Until this get fixed I'm not getting on Twitter at the moment, this is unacceptable. Especially from an account that I use focused on Japanese stuff but getting non-Japanese (in other words: 'localized' - based on location, maybe IP?) ads that are irrelevant (my account is based in the US, unfortunately).

**Comment by rcanada** [comment]
I can confirm that I just started seeing ads by gold checkmark accounts in my timeline today. I am using the website, twitter.com, and the Chrome Browser on a Chromebook.

**Comment by Tagishsimon** [comment]
Can confirm per rcanada - gold checkmarked ads are appearing when using the website - twitter.com - on Firefox/macOS

**Comment by insin** [comment]
Twitter have reverted a change they made to their timeline in June - tracking the fix in #408

**Comment by turekg** [comment]
Sorry, this was not fixed. More and more Ads are appearing again
