### ISSUE TITLE
Same content on Following and Retweets tabs

### ISSUE THREAD

**Issue by Tagishsimon** [insin/control-panel-for-twitter#407]
Using twitter.com website on firefox/macOS, the contents of the Following tab are identical to the contents of the Retweets tab - extension is no longer segregating posts from people I follow, from retweets by people I follow.

This started to happen in the last few hours; presumably the format emitted by twitter has changed.

Thank you for the extension - without it twitter would be unbearable.

**Comment by insin** [comment]
Twitter have reverted a change they made to their timeline in June - tracking the fix in https://github.com/insin/control-panel-for-twitter/issues/408
