### ISSUE TITLE
Restore old method of viewing post engagements (likes, reposts, QRTs)

### ISSUE THREAD

**Issue by breakthetargets** [insin/control-panel-for-twitter#414]
Recently Twitter just pushed out a new update which makes viewing engagements on any tweet obtuse. 

![image](https://github.com/insin/control-panel-for-twitter/assets/81792782/3007f542-7845-466d-b270-10a627053b1e)

As you can see above you can only see the quantity of people's actions. There's no more text to click on to view them. Now you have to click on the three dots and press on "View post engagements" as shown below.

![image](https://github.com/insin/control-panel-for-twitter/assets/81792782/d873fa4e-f4e7-40ee-bb2b-9e65310ca1db)

The post engagements is basically it's own page now that allows you to choose what engagement to view as seen below.

![image](https://github.com/insin/control-panel-for-twitter/assets/81792782/043fc96c-3a36-40e1-9bd7-c8086dc3fcd8)

I personally think this is a big downgrade and would love to see it restored somehow in a way, even if it means to just link directly to the respective engagement within the post engagements page itself.

**Comment by pixiekat** [comment]
It really goes to show you how awful Twitter's changes are that I came here to post this same issue and it's already been done. :)

**Comment by insin** [comment]
Reference for the old implementation we'll be restoring:

https://web.archive.org/web/20220707151054/https://twitter.com/actioncookbook/status/684515262712967170

**Comment by insin** [comment]
![image](https://github.com/insin/control-panel-for-twitter/assets/226692/f3d20469-6eb7-4258-bf41-d23aa1e2fe76)

**Comment by leo1115** [comment]
hello, can you do something about when there are no quotes on a tweet but you want to see reposts/likes 

![image](https://github.com/insin/control-panel-for-twitter/assets/54549454/44298e92-76ac-4ffc-a618-1ad53d1faaad)
