### ISSUE TITLE
Possible to expand "What's happening"?

### ISSUE THREAD

**Issue by rpodric** [insin/control-panel-for-twitter#417]
I know the more popular choice would be to hide it entirely, and there's an option for that already, but is there any kind of css/js trickery which might make it show more than the 4 or 5 items that it does now (I mean on the home page, without clicking "Show more"). There's a lot of space in that column, after all. I'm thinking more of the way Tweetdeck used to do it.

Thanks

**Comment by insin** [comment]
Sorry, there's no built-in Twitter functionality we can trigger to do this
