### ISSUE TITLE
Citations not appearing anymore

### ISSUE THREAD

**Issue by Purashido** [insin/control-panel-for-twitter#419]
Can affirm this because I checked posts I knew there was citations on them (Also, confirmed with the non-purged version I have on android). I looked at every option of the addon to be sure I just didn't hide them or that they weren't hided by a new feature, without success. I didn't change anything before this problem appeared nor added another addon, so I guess it may be a bug?

**Comment by Purashido** [comment]
Updating because I only noticied that I couldn't check who liked the tweets either.

**Comment by Hans5958** [comment]
Did you mean "Post engagements" or who liked, quoted, or retweeted/reposted the tweet/post? If so, that this is still possible to see by adding `/quotes`, `/retweets`, and `/likes`.

- https://twitter.com/KyivIndependent/status/1702170412103139568/quotes
- https://twitter.com/KyivIndependent/status/1702170412103139568/retweets
- https://twitter.com/KyivIndependent/status/1702170412103139568/likes

Even so, I hope this extension can bring the feature back, having an easy access of these links instead.

**Comment by Purashido** [comment]
Yes, it's those. Thank you for the tips, I forgot I could do that too.
I don't know if other people have this issue, but I hope it will come back too. It's a little inconvenient.

**Comment by insin** [comment]
We've now added options to restore all these links after Twitter removed them.
