### ISSUE TITLE
[Feature Request]: Revert "Copy Link" button functionality to share link via the Twitter domain, rather than the "X" domain

### ISSUE THREAD

**Issue by joshcawthorne** [insin/control-panel-for-twitter#423]
At some point recently, Musk had the "Copy Link" option found within the share sheet in tweets updated to copy the X domain to clipboard, rather than the Twitter one. It's one of the few things to remind me of the X rebrand, so I'd love it if I'd be able to tweak the functionality to revert the domain back to twitter.com until such time as the domain stops working altogether!

**Comment by linkthehylian** [comment]
This has already been requested at https://github.com/insin/control-panel-for-twitter/issues/413#issuecomment-1716877996. 

Owner has explicitly elaborated that this is a change they're not going to make.


For those wanting to stay with sharing tweets with the Twitter domain. Click on the tweet that you want to share and copy the link from the address bar in your browser instead.
![Capture](https://github.com/insin/control-panel-for-twitter/assets/20933012/5da11df0-236b-46a6-91d4-ca1bc24681ea)
