### ISSUE TITLE
iOS feature not working: No "Open app" nag in tweet header

### ISSUE THREAD

**Issue by simpzan** [insin/control-panel-for-twitter#428]
Hi there. 
I just bought the app on iOS app store. The extension works great except one feature: hide "open app" header. Could you have a look at this issue? Thanks! 

I am on iOS 16.6.1 safari.

**Comment by insin** [comment]
Do you have a screenshot of what you're seeing?

If it sits above Twitter and looks like the one in [this issue](https://github.com/insin/control-panel-for-twitter/issues/311), the only way to remove it is to uninstall the official Twitter app. That's a Safari feature we have no control over.

If the buttons inside Twitter itself have returned (they used to be on the top-right when viewing a Tweet, but I think they've removed them now) then we can do something about it.

**Comment by simpzan** [comment]
![IMG_0327](https://github.com/insin/control-panel-for-twitter/assets/366578/1c059a39-e99b-4c99-aec7-9ef3b5f933c5)
Yes I installed the X app. Uninstall the app fixed this issue, though not perfect fix. 
anyway, thank you.

**Comment by insin** [comment]
Added an FAQ for this to the website:

https://jbscript.dev/control-panel-for-twitter#safari-faq-ios-app-banner
