### ISSUE TITLE
[Feature request] Bring back old news headline style thumbnails 

### ISSUE THREAD

**Issue by 95Midnight** [insin/control-panel-for-twitter#435]
The mElon removed the news headlines recently because due to "aesthetics". I think it should have a option to bring it back 

https://www.theverge.com/2023/10/4/23903859/x-elon-musk-headlines-links-image-twitter

![image](https://github.com/insin/control-panel-for-twitter/assets/145422577/964b4f7a-d824-4638-91af-5842053922c3)

**Comment by insin** [comment]
Where would we get the titles from?

**Comment by insin** [comment]
Looks like it's still in the markup, should be doable as long as they retain this:

https://twitter.com/ControlPanelFT/status/1709849532597760404
