### ISSUE TITLE
bring back article titles

### ISSUE THREAD

**Issue by yukulele** [insin/control-panel-for-twitter#437]
Twitter has decided to remove the titles of links to articles and display only an image.

Only the domain name is displayed, but too discreetly.

- It's hard to tell the difference between an article and a simple image.
- the image doesn't always tell you what the article is about.
- there's a risk of scamming.

**Comment by insin** [comment]
Already done in v3.20.0: https://github.com/insin/control-panel-for-twitter/releases/tag/v3.20.0

**Comment by E5ten** [comment]
Will that new release be on firefox soon?

**Comment by insin** [comment]
Firefox Add-ons has recently been taking up to 4 days to review and approve new versions.

**Comment by E5ten** [comment]
> Firefox Add-ons has recently been taking up to 4 days to review and approve new versions.

Gotcha, thanks for all your work making the site usable
