### ISSUE TITLE
Add topics on timeline tweets

### ISSUE THREAD

**Issue by Hans5958** [insin/control-panel-for-twitter#442]
I'm not sure wheter this is suggested, but I tried searching any existing issues and I can't find it. It might be caused of my wrong keywords. Please close if this is a duplicate.

Lately, topics are shown on tweets that are located on the timeline. These days, it is hidden on the timeline, but you can still view what topic is from by opening the tweet. I want to differentiate these type of tweets while scrolling it, and I would appreciate of the feature if it is feasable

### Comparison between topical tweet on the time line (left) and topical tweet view (right)

![image](https://github.com/insin/control-panel-for-twitter/assets/11584103/bf30e0b3-1433-4c80-b0b6-cc8e43cfeafd)

### Reference of prior work

From [ourtechroom.com](https://ourtechroom.com/fix/turnoff-topic-suggestions-and-interests-on-twitter/)

![1twitter_more_option](https://github.com/insin/control-panel-for-twitter/assets/11584103/6d170bc2-7caf-4678-83b0-4fb6d042b5af)

**Comment by insin** [comment]
We can't restore this
