### ISSUE TITLE
Seem to have lost Retweets tab in Firefox/web

### ISSUE THREAD

**Issue by Tagishsimon** [insin/control-panel-for-twitter#455]
Using 3.21.2 on Firefox web browser (118.0.2 on MacOS), the Following / Retweets tabs seem to have disappeared. There's a single feed of what seems to be Following, fullstop.
<img width="1173" alt="Screenshot 2023-10-26 at 00 25 13" src="https://github.com/insin/control-panel-for-twitter/assets/9000789/73303bdf-a32c-4a1f-b64a-e71786a6ec9a">
<img width="704" alt="Screenshot 2023-10-26 at 00 27 03" src="https://github.com/insin/control-panel-for-twitter/assets/9000789/542e4b9b-ec30-413e-916f-338e1825d7c5">

**Comment by Serpari** [comment]
Same issue here.

![screenshot-twitter com-2023 10 25-19_51_02](https://github.com/insin/control-panel-for-twitter/assets/104118138/0e134341-d3d4-4d75-aba2-4c9293384c20)

**Comment by kohai-ut** [comment]
Ditto.  Using Brave
extension version 3.21.2

**Comment by insin** [comment]
Twitter removed the Home heading from the desktop timeline, so the default 'Hide the "Home" heading' feature is now hiding the tabs instead. You can disable it manually to fix this for now, and the feature will be removed in the next version.
