### ISSUE TITLE
Feature Request: Remove Grok Button

### ISSUE THREAD

**Issue by ClockworkCorvus** [insin/control-panel-for-twitter#474]
In Elon's ongoing crusade to make this website even worse, he's now made an AI that scrapes the entire website to train itself, and now it has its own button on the sidebar despite not even being accessible to people who aren't gullible enough to buy premium.

Just adding a toggle to remove the button from my sight would be a wonderful addition.

**Comment by insin** [comment]
I don't have it yet, will remove it when I get it

**Comment by nokel** [comment]
I had this pop up today 
![image](https://github.com/insin/control-panel-for-twitter/assets/13248734/6242914a-fed4-4b83-8174-c8174544547b)

Is it possible to make the extension detect a new change in the sidebar and either automatically remove it or ignore the change depending on what you ask it to do?
