### ISSUE TITLE
Feature Request: Return the View QRTs button that Twitter used to have

### ISSUE THREAD

**Issue by ClockworkCorvus** [insin/control-panel-for-twitter#475]
You used to be able to just click a button to view QRTs directly on the post, but now you have to click the three dots, and then go to view post engagements. Twitter removed that a while back, if there is some way to re-add that feature, it would be very welcome.

**Comment by insin** [comment]
It's already being restored by default, but we only show it if Twitter indicates the tweet you're looking at has some QTs (which can be missing or sometimes inaccurate)

![Screenshot_2023-12-09-15-58-23-68_984e1414ae90666a90f12ff17ec14a7f](https://github.com/insin/control-panel-for-twitter/assets/226692/599c7f9c-5228-4f75-bf3e-35d61fc3de68)

![Screenshot_2023-12-09-15-57-38-39_984e1414ae90666a90f12ff17ec14a7f](https://github.com/insin/control-panel-for-twitter/assets/226692/ab782821-bcba-4888-aa50-fe3222d95fd3)
