### ISSUE TITLE
[Feature Request] Revert Media tab from displaying grid format

### ISSUE THREAD

**Issue by veckin** [insin/control-panel-for-twitter#476]
In addition to the browser adding the Grok feature, the Media tab currently displays all images in an Instagram-like grid format. There is also no option to toggle this back to the original format.

Example (screenshot mine):
![panel_120923](https://github.com/insin/control-panel-for-twitter/assets/81895704/2ed32993-ca08-4d9f-95ea-afb3e248b8df)

**Comment by Velken** [comment]
"Old Twitter Layout" extension has the un-gridfied media tab, but it also has a lot of other changes to the website

**Comment by insin** [comment]
We can't do this one, it would require a complete re-implementation (which is what Old Twitter Layout does for the entire site)
