### ISSUE TITLE
[Bug?] Twitter bird logo turns purple in incognito mode

### ISSUE THREAD

**Issue by whiteangel123** [insin/control-panel-for-twitter#478]
Not sure if this is supposed to happen or not, but the top left Twitter logo turns purple in incognito, whether it's on Chrome or Firefox. 
![image](https://github.com/insin/control-panel-for-twitter/assets/36785520/b5c09400-0cef-430a-b4f3-63a8a922dfce)

**Comment by itagagaki** [comment]
Does this extension work in incognito mode?
Anyway, you might be interested in #466.

**Comment by whiteangel123** [comment]
It does work in Incognito. Thank you, that works!

**Comment by insin** [comment]
This is already fixed for the next release, coming soon
