### ISSUE TITLE
[Request] Return link font back to original font

### ISSUE THREAD

**Issue by nokel** [insin/control-panel-for-twitter#480]
Hi, I noticed over the past few days that the font in a link's description was changed a different font, would you be able to revert it back to the original Segoe UI(?) font please?

![image](https://github.com/insin/control-panel-for-twitter/assets/13248734/2a7cdda2-e24e-45c3-9b42-af8858e60dc6)

**Comment by nokel** [comment]
I just noticed that this post is also mentioning the change, however it's showing more than just the link font for them...
https://github.com/insin/control-panel-for-twitter/issues/479

**Comment by aliceisjustplaying** [comment]
For now if you add the rule `||abs.twimg.com/fonts/v1/*` to uBlock Origin it'll block the font and will look less bad. This will probably block the regular Chirp font as well.

**Comment by nokel** [comment]
Yup, seems like it does the job for now, thanks!
