### ISSUE TITLE
[Feature Request] Remove "Live on X" from user profile viewing

### ISSUE THREAD

**Issue by DarkRespite** [insin/control-panel-for-twitter#482]
This panel appears now when viewing a user's profile, including my own.

Looks like this started about the same time as the Grok addition (thank you for hopefully removing that soon) and the Chirp font override (thank you for also hopefully removing that soon).

![image](https://github.com/insin/control-panel-for-twitter/assets/153543971/57a54ca6-799e-4bdb-aa17-b93c94dbbe8d)

**Comment by insin** [comment]
The sidebar had a special case to allow the media box to display when viewing profile pages - now that box has been removed, this box is accidentally being shown instead - we can remove that special case, which should fix this.

Those other changes are on the way 🥷
