### ISSUE TITLE
"Hide Views under tweets" is not working, I'm seeing the Views count again

### ISSUE THREAD

**Issue by zdgra** [insin/control-panel-for-twitter#485]
Hi, I've always had the "Hide Views under tweets" toggle on and I wasn't seeing the View count, but today I noticed that the View count is showing up, even with the "Hide Views under tweets" toggle still on. 

Thanks!

**Comment by insin** [comment]
Has Twitter moved the view count for you? Everything still looks the same to me.

It took me a couple of days to finally get the new Grok menu item to test hiding it, so screenshots of what's happening would be useful.

**Comment by zdgra** [comment]
![IMG_7095](https://github.com/insin/control-panel-for-twitter/assets/76718657/e859b444-16b3-430e-9beb-5daa14c93069)
![IMG_7096](https://github.com/insin/control-panel-for-twitter/assets/76718657/6e33b190-0a2b-47c8-a61e-ec2e64a55d64)

**Comment by godkarmachine** [comment]
Also seeing this issue, using the extension on Android Firefox Beta.
