### ISSUE TITLE
[Feature Request] Remove clickability of own profile button.

### ISSUE THREAD

**Issue by ecceeecs** [insin/control-panel-for-twitter#487]
I have a compulsive habit of checking my profile and, by extension, my tweets and likes. Is it possible to disappear one's profile button from the sidebar, as well as disable clicking on own's profile image /username to access their profile? A small elision, but it would do a lot for people like me. Of course, typing in my username would lead me to my account, but it would require some time. Thank you.

**Comment by insin** [comment]
This is maybe a bit too specific a feature for Control Panel for Twitter, but it's something that's easily done with a userstyles extension like [Stylus](https://github.com/openstyles/stylus/#stylus)

If you replace the link target in this CSS rule with your own Twitter username, then any and all links to your profile wil do nothing when clicked:

```css
a[href="/jbscript"] {
  pointer-events: none;
}
```

**Comment by ecceeecs** [comment]
Hi, if anyone has this issue, I recommend the "Click to Remove Element" plugin for Chrome.
