### ISSUE TITLE
Highlights tab on your own profile is a Premium upsell - hide it

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-twitter#488]
Hide the Highlights tab if:
- Hiding upsells is enabled
- The profile you're looking at is your own (profile header has an Edit Profile link which goes to `/settings/profile`)
- You're not subscribed to Premium (profile header doesn't have a `[data-testid="icon-verified"]`

**Comment by emihead** [comment]
will this apply to the articles tab as well?

**Comment by insin** [comment]
Fixed in 8797de06e7b00182c6c4229ea7d5b73666d72efc - also hides the Articles tab
