### ISSUE TITLE
Open app nag still appears if toggled on

### ISSUE THREAD

**Issue by Grapplerone** [insin/control-panel-for-twitter#491]
When toggling ON the open in app nag you still get the nag at the top of the screen at all times.

![image](https://github.com/insin/control-panel-for-twitter/assets/8892548/8392276b-962f-4fe9-b7a2-76ba48558002)

**Comment by insin** [comment]
That's a Safari feature we have no control over, see the FAQ here: https://jbscript.dev/control-panel-for-twitter#safari-faq-ios-app-banner
