### ISSUE TITLE
The company changed the looks of link card

### ISSUE THREAD

**Issue by nagato7** [insin/control-panel-for-twitter#499]
[Relative article](https://9to5google.com/2024/01/04/twitter-x-headlines-link-preview/)

When "Restore Headlines..." option is turned on, it still shows "From URL" text under the card, which is redundant.

**Comment by insin** [comment]
Have been waiting for whatever they were doing to be consistent before we reacted, will sort these out

![Screenshot_2024-01-05-16-54-36-78_984e1414ae90666a90f12ff17ec14a7f](https://github.com/insin/control-panel-for-twitter/assets/226692/0579f0e4-7837-4807-aa5e-32780cc08622)
