### ISSUE TITLE
Hide "Pro" / tweetdeck from menu

### ISSUE THREAD

**Issue by dav1312** [insin/control-panel-for-twitter#505]
![image](https://github.com/insin/control-panel-for-twitter/assets/63931154/8148f0ec-ac91-4fb2-912e-1eea32b3a01e)

**Comment by insin** [comment]
![Screenshot 2024-01-19 at 9 59 32 am](https://github.com/insin/control-panel-for-twitter/assets/226692/737a56ca-41cc-4373-9d52-ad1046834ef0)
