### ISSUE TITLE
Why is there an X Premium (Twitter Blue) tab icon on the lower right (mobile)?

### ISSUE THREAD

**Issue by ryandtw** [insin/control-panel-for-twitter#527]
That's another upsell gateway 😡
![IMG_1056](https://github.com/insin/control-panel-for-twitter/assets/37318146/dd3e3017-eb16-43b3-a92a-84e52b5efff5)

**Comment by insin** [comment]
I'm not seeing this version in my region yet, but I'll remove it when I get it

**Comment by QuinnyPig** [comment]
Yup, just showed up today. Honestly it's like whack-a-mole with these clowns...

**Comment by insin** [comment]
(😮)

Does it link to `/i/premium`? I can pre-emptively add something to zap it even before I've even got it.
