### ISSUE TITLE
Remove Mention of Rebranding "Never miss what’s happening on X by enabling push notifications"

### ISSUE THREAD

**Issue by attheshow** [insin/control-panel-for-twitter#532]
I recently noticed another mention of the rebranding in the message "Never miss what’s happening on X by enabling push notifications". I wonder if that could be updated to say Twitter? Thanks so much for all of your work on this! 😊

**Comment by insin** [comment]
We're hiding all those timeline prompts instead, coming in the next version:

d579c00

**Comment by attheshow** [comment]
Awesome. That sounds great!
