### ISSUE TITLE
[Feature Request] Show hidden content by default

### ISSUE THREAD

**Issue by Baramanga** [insin/control-panel-for-twitter#542]
Twitter has now auto flag entire accounts of artists it thinks it posting NSFW and now every picture is censored "sensitive" on their account. Is there a way to disable this? Thank you in advanced.

![GKYvdOyaIAAqhX8](https://github.com/insin/control-panel-for-twitter/assets/71797097/0c037676-3f08-4a69-9985-b173bb6461eb)

**Comment by lunarlabs** [comment]
I do not want to install another plugin to fix this issue, please implement ASAP

**Comment by FerretCodes** [comment]
Also wanted to kindly request this feature to be added, it's crippled my usage of the platform! Currently working around with this https://greasyfork.org/en/scripts/437359-twitter-hide-content-warning-crap

**Comment by FridisTheDragon** [comment]
also voicing my need for this feature, my twitter is now utterly unusable
