### ISSUE TITLE
[Issue] Restore quote tweets button and other interaction links not working

### ISSUE THREAD

**Issue by Venomousicon** [insin/control-panel-for-twitter#544]
Since yesterday, the restored quote tweets/likes/retweets buttons under a tweet have stopped appearing. I checked another extension, "Old Twitter Layout (2024)"; they still have the number of quotes listed, so I don't believe it's a Twitter API problem. 
I have all the necessary settings to restore the interaction links set to "true", and I've tried uninstalling and reinstalling the extension and making sure it's updated, but nothing seems to work.

**Comment by insin** [comment]
This should now be fixed in [v2.34.0](https://github.com/insin/control-panel-for-twitter/releases/tag/v3.24.0)
