### ISSUE TITLE
[Remove Premium upsells] Article tab reappears on selecting other tabs + Upsell on Likes tab

### ISSUE THREAD

**Issue by diyachan** [insin/control-panel-for-twitter#546]
opening another profile tab that isn't Tweets while removing Premium upsells makes the Articles tab reappears
![image](https://github.com/insin/control-panel-for-twitter/assets/7719971/a4fcb7e8-062b-48c9-a82c-3a0a4f11b093)

Upsells on own Likes tab
![image](https://github.com/insin/control-panel-for-twitter/assets/7719971/0058f28c-55fc-44a6-8922-01ebabd2d7b0)

**Comment by insin** [comment]
This might depend on the combination of features you have enabled, as it's working for me, but will have a look

![firefox_Zwcq3DLbjJ](https://github.com/insin/control-panel-for-twitter/assets/226692/e7569c7e-f076-4ea9-8ba3-36a9295d3db6)
