### ISSUE TITLE
Ads appearing again 🤬

### ISSUE THREAD

**Issue by ryandtw** [insin/control-panel-for-twitter#559]
I was browsing a Twitter profile (@jetcoasterotoko, 'verified') on my iPhone using Safari and the Control Panel extension, language set to Japanese, IP address is in Seattle...and I saw a RIDGE WALLET (🖕) AD.

X...I mean Twitter has screwed up again 🤬

…えっ？()←

If anyone is seeing ads even with Control Panel as of today (Monday, 5/13/2024) please feel free to let us know.

Sorry for the inconvenience 😣 (I'm going to have to use remote desktop and OldTwitter extension for now until the issue is fixed)

**Comment by insin** [comment]
Twitter just deployed some changes which broke some of our functionality - it looks like the ad format hasn't changed, so it was likely something else which stopped Control Panel from working on that profile - looking into it.

**Comment by insin** [comment]
Figured out what's causing this - the main content element in user profiles is now rendered asynchronously, but we assume it will be available immediately

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/358ceb87-7ec7-4775-84f9-3e5a8696ea17)

If this error happens, you need to refresh to get Control Panel for Twitter working again

Will fix this in the next release - this should also fix #559

**Comment by insin** [comment]
This might be the cause - after the recent Twitter update, the title of the first user profile you visit "sticks", which breaks Control Panel for Twitter's page change/current page detection:

![firefox_N41NH6EbNU](https://github.com/insin/control-panel-for-twitter/assets/226692/1fecfcba-e593-4b98-b5f0-4240b06613e9)

**Comment by boilinabag** [comment]
usa here. i  am glad i'm not the only one who is seeing something going on. i toggled the who to follow, and it went away. we'll see when i reboot, if it returns. looks like old tweetdeck is seeing issues too. oh, and i use brave, ublock, ghostery, and a vpn, so i am not seeing any ads so far...........................
