### ISSUE TITLE
Is there a way to give permissions to run this on x.com?

### ISSUE THREAD

**Issue by LAC-Tech** [insin/control-panel-for-twitter#562]
twitter.com is starting to automatically re-direct to x.com. Not sure if it's happening for everyone or they're just rolling it out for certain users, but it's happening across both my machines.

Once you're on x.com, the extension doesn't run. My understanding is that because x.com isn't on the permissions list, only twitter.com and mobile.twitter.com.

Could x.com be added to the list of domains? Alternatively, is this something users can fix locally?

**Comment by insin** [comment]
The next version will add x.com permissions https://github.com/insin/control-panel-for-twitter/commit/2ce64786d12c112a7bbfec2bc18a7fd1b5d4094d
