### ISSUE TITLE
x.com redirect

### ISSUE THREAD

**Issue by dark-swordsman** [insin/control-panel-for-twitter#568]
It appears that they are now forcing Twitter.com to redirect to X.com. Also, for some reason, the extension does not work on x.com.

![image](https://github.com/insin/control-panel-for-twitter/assets/7909209/25249785-ae2e-4470-92fa-e99606a71716)

![image](https://github.com/insin/control-panel-for-twitter/assets/7909209/d58bd908-dc8a-41fc-96cf-7a72eff3ebdf)

**Comment by pkpc99** [comment]
x.com redirect support was added in [Release 4.0.0](https://github.com/insin/control-panel-for-twitter/releases/tag/v4.0.0)
I upgraded to that version, and x.com is working for me now

**Comment by coolandsmartrr** [comment]
Problem: I have version 3.24.0 installed, and my Firefox (version 126.0 on Mac) does not recognize that a new version (version 4.0.0) is available for download. How do I force Firefox to update this extension?

Things I tried:
- Update Firefox
- Turn off "Allow Automatic Updates" for this extension, click on Check for Updates (as described [here](https://support.mozilla.org/en-US/kb/how-update-add-ons))

I do not want to remove and re-install this, as I do not want to lose my personal preferences.

**Comment by insin** [comment]
Just running Check for Updates should do it

**Comment by dark-swordsman** [comment]
Seems to work now. Thank you <3
