### ISSUE TITLE
forced x.com link change breaks extension on chrome

### ISSUE THREAD

**Issue by Kaill3r** [insin/control-panel-for-twitter#571]
Now that people are being redirected to x.com rather than twitter.com, the extension seems to no longer work on google chrome, with it stating "no access is needed" and that it can't rewrite anything on the site. All of the features from the app appear to be gone as well, just to corroborate this fact. All was working fine until the url change, so i have no reason to believe it's anything else.

**Comment by Basedfloppa** [comment]
Same on firefox

**Comment by insin** [comment]
Support for the x.com domain was added in [V4.0.0](https://github.com/insin/control-panel-for-twitter/releases/tag/v4.0.0) - check you have the latest version installed and you've given it permissions for x.com

**Comment by Eduardolicious** [comment]
adding to the others, on v4.0.0, permissions are good, twitter is all borked. especially opening a tweet with a middleclick, which sends the new tab back to x.com and gives up
![image](https://github.com/insin/control-panel-for-twitter/assets/67165184/485f34f3-c0bf-4612-a632-af4e662d472b)

**Comment by jamesastound** [comment]
I had to restart Firefox before it showed me the update from 3.x. Clicking the check for updates feature didn't work.

**Comment by Baramanga** [comment]
> I had to restart Firefox before it showed me the update from 3.x. Clicking the check for updates feature didn't work.

This happened to me too. Tho I just remove and then reinstall the extension

**Comment by Kaill3r** [comment]
had to uninstall and reinstall the extension to get 4.0.0 but can confirm it works again now
