### ISSUE TITLE
[Bug Report] "For You" tab returns on homepage after viewing likes tab on own profile

### ISSUE THREAD

**Issue by di0-s** [insin/control-panel-for-twitter#572]
If you have the algorithmic "For You" tab hidden, it becomes visible again after you view the likes tab from your own profile, then go back to your Twitter homepage.

**Comment by insin** [comment]
Twitter currently has a bug where viewing a profile breaks the page title (if you go back to Home it will still have the profile's title), which breaks Control Panel for Twittter.

I thought they'd have fixed it by now (it's been a few days), but will see if we can put in a temporary workaround..
