### ISSUE TITLE
"Hide the 'For You' timeline" preference also hides the "Top" tab for searches

### ISSUE THREAD

**Issue by ToadKing** [insin/control-panel-for-twitter#576]
Enabling this setting hides the "Top" tab on search lists, making it so you can't navigate back to it if you select a different sort (like Latest/Media/etc.)

**Comment by insin** [comment]
I'm not seeing this on desktop or mobile, could you show me what you mean?

![Screenshot 2024-05-19 at 6 52 37 PM](https://github.com/insin/control-panel-for-twitter/assets/226692/10abf8f5-de07-4d4f-87a5-09d9abef5fc7)

![Screenshot 2024-05-19 at 6 53 01 PM](https://github.com/insin/control-panel-for-twitter/assets/226692/bd18cc86-b65c-4941-8c55-d7a80aacae9f)

**Comment by ToadKing** [comment]
Hmm, it seems to be working now. Not sure what caused the issue.

Guess I'll close this for now and re-open for more reproduction steps if it happens again.
