### ISSUE TITLE
New type of ads

### ISSUE THREAD

**Issue by jdschuitemaker** [insin/control-panel-for-twitter#578]
Today I noticed in my timeline for the first time that an "Ad" is showing. See the word "Ad" in the top-right. This one is with an image, I saw another one that just had text and looked very similar to a normal tweet.

![image](https://github.com/insin/control-panel-for-twitter/assets/2353413/7c6d5991-c965-48ee-af6d-a047ce51d13e)

Could this kind of tweet be removed?

**Comment by insin** [comment]
That's just what Ads on Twitter look like now, maybe it's been so long since you last saw one.

If you're not running v4.1.0 you were probably being affected by the Twitter bug it has a workaround for.

**Comment by jdschuitemaker** [comment]
That's it probably then... Thank you.
