### ISSUE TITLE
x.com redirect is disabling most/all features? (firefox)

### ISSUE THREAD

**Issue by bzellers** [insin/control-panel-for-twitter#586]
Looks like since Twitter now redirects to X.com that since the extension doesn't have permissions on x.com, it fails to do anything.

**Comment by Nadahar** [comment]
I have this problem too - I have to manually edit the URL to twitter.com instead of x.com to make it work. Is there any way to prevent the redirection, or to make this add-on work for x.com as well?

**Comment by NotBlankyu** [comment]
The extension should ask for permissions for x.com, if it doesn't try reinstalling

**Comment by Nadahar** [comment]
> The extension should ask for permissions for x.com, if it doesn't try reinstalling

When i tried to update it "manually" it asked for permissions for x.com as well.

**Comment by bzellers** [comment]
It prompted me last night to allow x.com permissions, so it seems like it's fixed now.
