### ISSUE TITLE
For You tab showing much more irrelevant tweets

### ISSUE THREAD

**Issue by 97iu** [insin/control-panel-for-twitter#590]
Prior to the migration to X, the For You tab looked more like a Following tab ranked by popularity (as in media tweets and tweets with more likes ranked first). Now there is a huge amount of political debate tweets on For You and Following is chronologically ordered so I have to go through chitchats and lunch pics of the people I follow to see the artwork I follow them for. Will there be an option to bring the popularity ranked following For You tab back?

**Comment by Primeey** [comment]
Control Panel for Twitter doesn't change how many irrelevant or relevant tweets you see. It doesn't have that power, that's on X's side with their algorithm.

**Comment by 97iu** [comment]
> Control Panel for Twitter doesn't change how many irrelevant or relevant tweets you see. It doesn't have that power, that's on X's side with their algorithm.

Thanks, I finally discovered the random stuff happens because of "twitter interests" and unchecked everything.
