### ISSUE TITLE
Edge

### ISSUE THREAD

**Issue by flezus** [insin/control-panel-for-twitter#604]
Hi, I'm using an extension on Microsoft Edge, but there's no update available for it. I've noticed that there have been over 3 updates for other browsers, but not for Microsoft Edge.

**Comment by insin** [comment]
Edge takes up to 7 business days to approve new versions - if you want to ensure you're always on the latest version, you can install extensions from the Chrome Web Store in Edge, and Chrome tends to be the first to approve new versions of Control Panel for Twitter

https://chromewebstore.google.com/detail/control-panel-for-twitter/kpmjjdhbcfebfjgdnpjagcndoelnidfj
