### ISSUE TITLE
View Post Engagement hide or unhide not working

### ISSUE THREAD

**Issue by iii-iii** [insin/control-panel-for-twitter#627]
This option does not make a difference whether it is checked or unchecked.

**Comment by insin** [comment]
If you have "Restore Quote Tweets link under Tweets" enabled, it also currently replaces the "View Post Enagagements" link under your own Tweets, as they take you to the same screeen

**Comment by iii-iii** [comment]
> If you have "Restore Quote Tweets link under Tweets" enabled, it also currently replaces the "View Post Enagagements" link under your own Tweets, as they take you to the same screeen

Thanks, I have it working. But I did not see any "quote tweet link" anyway.
