### ISSUE TITLE
[Feature Request] Add an option to change the default 'Sort Replies' option.

### ISSUE THREAD

**Issue by Kiznel** [insin/control-panel-for-twitter#630]
Twitter/X added a new drop-down option to replies, allowing you to sort by 'Most relevant', 'Most recent', and 'Most liked'. Only issue is that there isn't an option to save a default option.

It would be an amazing addition to this extension to be able to automatically sort by one of these 3, when you first load the comments under a tweet.

![chrome_eyImSuVH5Q](https://github.com/user-attachments/assets/6d310fea-66e9-40b1-96cc-b42f95501d2d)

**Comment by insin** [comment]
This was added in v4.2.1: https://github.com/insin/control-panel-for-twitter/releases/tag/v4.2.1
