### ISSUE TITLE
リスト上部に固定機能を復活させることはできないか？/Can we bring back the pin to the top of the list feature?

### ISSUE THREAD

**Issue by toppa0911** [insin/control-panel-for-twitter#632]
※日本語原文
過去ブラウザ版Twitterで、リスト画面の上部に固定したリストを5つまで表示出来ていたのですが、
いつの間にか表示されず固定ができなくなりました。
この拡張機能で再度リストの上部固定機能を復活させて頂くことはできないでしょうか？
~~~~
※English Translation
In the past, with the browser version of Twitter, I was able to display up to five lists pinned to the top of the list screen,
but suddenly they stopped being displayed and I couldn't pin them.
Is it possible to bring back the pinning list function to the top with this extension?

**Comment by insin** [comment]
Unfortunately, we can't restore this feature - it would require us to completely re-implement the Twitter timeline

> 残念ながら、この機能を復元することはできません。Twitterのタイムラインを完全に再実装する必要があります

**Comment by toppa0911** [comment]
理解しました。残念ですが諦めます。ご丁寧に返信して頂きありがとうございました。

> I understand. Unfortunately, I will give up. Thank you for your kind reply.
