### ISSUE TITLE
Resume hiding placeholders for replies from muted accounts

### ISSUE THREAD

**Issue by rogela** [insin/control-panel-for-twitter#658]
Replies from muted accounts to a tweet used to be hidden completely without placeholders, but this seems to have been changed after recent update. Would like this functionality back.
![IMG_3650](https://github.com/user-attachments/assets/9d9e43a4-314c-47d3-91a3-277dffa04273)

**Comment by insin** [comment]
It looks like we pulled the wrong translation for the "View" button out of Twitter's Japanese locale, which is what we look for to hide these posts.

**Comment by insin** [comment]
This isn't present in the client locale data, so it must be a server-side translation - we'll have to manually check this for every language.

![Screenshot 2024-10-13 at 9 32 41 am](https://github.com/user-attachments/assets/6e1fdf1b-ac9a-45c9-83be-fb4aa5020e16)
